In [19]:
import numpy as np

def findLowestEntropy(array):
    lowestEntropy = float('inf')
    lowestEntropyArray = []
    for i in range(len(array)):
        for j, entropy in enumerate(array[i]):
            if entropy < lowestEntropy:
                lowestEntropyArray = []
                lowestEntropy = array[i][j]
                lowestEntropyArray.append([(i,j), lowestEntropy])
            elif (entropy == lowestEntropy):
                lowestEntropyArray.append([(i,j), lowestEntropy])
    return lowestEntropyArray

def initializeArray(array):
    for i in range(len(array)):
        for j in range(len(array[i])):
            array[i][j] = np.random.randint(2,10)
    return array

randomArray = np.random.randint(2,10,size=(10,10))

print(randomArray)

findLowestEntropy(randomArray)

[[2 8 8 6 3 3 6 7 3 3]
 [4 6 9 3 3 9 8 9 9 5]
 [6 7 7 7 6 6 9 4 4 7]
 [2 8 6 4 7 4 9 9 4 3]
 [6 3 4 6 9 8 8 9 4 8]
 [9 8 9 4 4 4 7 8 7 2]
 [5 9 7 4 3 3 4 7 8 7]
 [8 2 9 7 2 2 3 6 2 5]
 [8 9 6 9 7 7 9 2 7 5]
 [8 4 2 2 4 3 6 7 4 4]]


[[(0, 0), 2],
 [(3, 0), 2],
 [(5, 9), 2],
 [(7, 1), 2],
 [(7, 4), 2],
 [(7, 5), 2],
 [(7, 8), 2],
 [(8, 7), 2],
 [(9, 2), 2],
 [(9, 3), 2]]

In [24]:
map_data = np.full((10, 10),5)
print(map_data)

TypeError: Cannot interpret '10' as a data type